### ISSUE TITLE
Compile for glibc 2.17

### ISSUE THREAD

**Issue by AndriyMulyar** [tamuhey/tokenizations#6]
Great implementation and solved my problem locally! When trying to run on a Centos based cluster, I found that the library was compiled at minimum for GLIBC_2.18. Would it be feasible to compile against GLIBC_2.17?

**Comment by tamuhey** [comment]
Thank you for your report! I'll try to solve this problem.
Could you share the environment information?

**Comment by tamuhey** [comment]
I repro it in `centos:7` docker image

**Comment by tamuhey** [comment]
@AndriyMulyar I've published a new version of `pytokenizations` which is able to be installed in old centos (#7) . Please try it!

**Comment by AndriyMulyar** [comment]
Thank you!
